### PR TITLE
Add board Silicognition LLC M4-Shim

### PR DESCRIPTION
**Pull request by xorbit**

### CODE REVIEW

**Review by dhalbert — APPROVED** [review]
Looks good!

**Comment by xorbit** [comment]
Thanks for merging.  I was hoping to have an officially released binary to give to my CM to program into the boards, how often are new versions typically generated?  My board is not yet included in the latest v3.10.0.

**Comment by dhalbert** [comment]
I can make a new release to get a clean version number. I'll do it in the next day or two.

**Comment by xorbit** [comment]
Thanks Dan!
Dumb question but where do the binaries actually go?  I haven't been able to find them.

**Comment by dhalbert** [comment]
> Dumb question but where do the binaries actually go? I haven't been able to find them.

Do you mean the release artifacts? They are in the releases (unlike CircuitPython): https://github.com/adafruit/uf2-samdx1/releases

**Comment by xorbit** [comment]
I saw you did the build, thank you Dan.
I still wonder how this gets updated on CircuitPython.org.  I added my board to the bootloaders file, but the page refers to a non-existent 3.10.0 bootloader instead of the latest.

**Comment by dhalbert** [comment]
I have to do it by hand. I will get started on it.

**Comment by xorbit** [comment]
I saw it was done, thanks you Dan.

**Pull request merged**
