### PR TITLE
Add support for StackRduino-M0-PRO

### PR DESCRIPTION
**Pull request by StackRduino**

### CODE REVIEW

**Review by dhalbert — CHANGES_REQUESTED** [review]
Looks good! Please change the `boards/StackRduino-M0-PRO` directory name to all lower-case, with underscores: `boards/stackrduino_m0_pro`. We can approve and merge after that.

**Comment by StackRduino** [comment]
Great Thanks, Please take a look now

**Review by dhalbert — APPROVED** [review]
Great! 

You can save multiple commits if you make the changes locally and then push them all at once. It requires learning local git, but it's worth it in the long run. But no issue now.

**Comment by dhalbert** [comment]
Here is a Learn Guide that might be helpful: https://learn.adafruit.com/contribute-to-circuitpython-with-git-and-github

**Comment by StackRduino** [comment]
Thanks a lot

**Pull request merged**
