### PR TITLE
Remove: invalid GCLK_GEN2 setting if defined CRYSTALLESS

### PR DESCRIPTION
**Pull request by turmary**

### CODE REVIEW

**Comment by dhalbert** [comment]
@turmary Did you see a problem when this was being done incorrectly, or is it just a cleanup? I'm just interested in how you noticed this, whether due to a problem or auditing the code.

**Comment by turmary** [comment]
OK, in my product I want add a watchdog to this bootloader.
https://github.com/ImagineXYZ/Remora/tree/master/Modular/Remora/libraries/Watchdog_SAMD21

If system_init() be called after the watchdog init, the USB works OK, but the dog timeout will too short.
So I am sure the DFLL48M works properly after this patch been done.
And the the GCLK_GEN2 setting in system_init() are conflict with library Watchdog_SAMD21 code.

Originally I think the DFLL48M should use GCLK_GEN2 as clk source, but that's not true.
The DFLL48M clock formula does't match the real input/output frequency if GCLK_GEN2 is the source,
so the code I removed are entirely obsolete.

**Comment by turmary** [comment]
If the GCLK_GEN2 been removed, nothing will incorrect, 
except a delay is required when switch between bootloader and application.
Incrementing space between USB disconnection and connection will help USB host to be more stable.

**Comment by dhalbert** [comment]
I am not ignoring this but need to study it in more detail.

**Comment by dhalbert** [comment]
Superseded by #188.

**Pull request closed without merging**
